// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedStat } from "./ParsedStat";

export type ParseResult = { text: string, stats: Array<ParsedStat>, };