// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParsedStat = { 
/**
 * The id of the row in Stats.dat
 */
id: string, 
/**
 * The template variable in the stat text (e.g. {0})
 */
index: number, 
/**
 * The value as read from the mod that was parsed
 */
parsedValue: number, 
/**
 * Approximate value of the raw value of this stat as per the game files
 * (for instance if the game stores the stat as ms but displays it as seconds,
 * this will be the ms value).
 */
baseValue: number, };