[package]
name = "poestat-wasm"
version = "0.1.0"
authors = ["ivy <lvlvllvlvllvlvl@users.noreply.github.com>"]
edition = "2018"
 
[dependencies]
wasm-bindgen = "0.2.70"
 
[lib]
path = "rs/lib.rs"
crate-type =["cdylib", "lib"]
