/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StatHandlers {
  [k: string]: IntHandler | RelationalData | CanonicalLine | Noop;
}
export interface IntHandler {
  addend?: number;
  divisor?: number;
  multiplier?: number;
  precision?: number;
  fixed?: boolean;
  type: "int";
}
export interface RelationalData {
  dat_file: string;
  index_column?: string;
  type: "relational";
  value_column: string;
  /**
   * Map from integer stat values to text associated with that value
   */
  values: {
    [k: string]: string;
  };
  predicate?: Predicate;
}
export interface Predicate {
  column?: string;
  value?: number;
}
export interface CanonicalLine {
  type: "string";
}
export interface Noop {
  type: "noop";
}
