name: publish demo site

on:
  workflow_dispatch:
  push:
    branches: ["develop"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pages
      - name: install bun
        uses: oven-sh/setup-bun@v1
      - name: bun install
        run: bun install
        working-directory: pages
      - name: build
        run: bun run build
        working-directory: pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
